//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicTacToe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запущенная копия программы или брандмаузер блокирует порт, необходимый для работы программы.
        /// </summary>
        internal static string Game_Init_Port_Is_No_Available {
            get {
                return ResourceManager.GetString("Game_Init_Port_Is_No_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошло отключение от клиента соперника.
        /// </summary>
        internal static string Game_ProtocolOnErrorMessage_ClientAborted {
            get {
                return ResourceManager.GetString("Game_ProtocolOnErrorMessage_ClientAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27015.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection... {0}.
        /// </summary>
        internal static string Protocol_PostGoGame_Connection {
            get {
                return ResourceManager.GetString("Protocol_PostGoGame_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы играете крестиками.
        /// </summary>
        internal static string TTTForm_YouGameDagger {
            get {
                return ResourceManager.GetString("TTTForm_YouGameDagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы играете ноликами.
        /// </summary>
        internal static string TTTForm_YouGameZero {
            get {
                return ResourceManager.GetString("TTTForm_YouGameZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш ход!.
        /// </summary>
        internal static string TTTForm_YouTurn {
            get {
                return ResourceManager.GetString("TTTForm_YouTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введен некорректный IP адресс.
        /// </summary>
        internal static string UIGameTTT_CreateGame_IP_Not_Correct {
            get {
                return ResourceManager.GetString("UIGameTTT_CreateGame_IP_Not_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничья!.
        /// </summary>
        internal static string UIGameTTT_Drawn {
            get {
                return ResourceManager.GetString("UIGameTTT_Drawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предложение игры от клиента с IP .
        /// </summary>
        internal static string UIGameTTT_OnGoNewGame_Client_with_IP {
            get {
                return ResourceManager.GetString("UIGameTTT_OnGoNewGame_Client_with_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая игра.
        /// </summary>
        internal static string UIGameTTT_OnGoNewGame_NewGame {
            get {
                return ResourceManager.GetString("UIGameTTT_OnGoNewGame_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        internal static string UIGameTTT_OnGoNewGameWarn {
            get {
                return ResourceManager.GetString("UIGameTTT_OnGoNewGameWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы проиграли.
        /// </summary>
        internal static string UIGameTTT_You_Miss {
            get {
                return ResourceManager.GetString("UIGameTTT_You_Miss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы победили!.
        /// </summary>
        internal static string UIGameTTT_You_Win {
            get {
                return ResourceManager.GetString("UIGameTTT_You_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не корректный формат IP.
        /// </summary>
        internal static string UINewGame_ConnectButtonClick_IncorrectIPFormat {
            get {
                return ResourceManager.GetString("UINewGame_ConnectButtonClick_IncorrectIPFormat", resourceCulture);
            }
        }
    }
}
